import { approvedPairs, forbiddenPairs } from "../contrast-pairs.ts";
import { contrastRatio } from "./contrast.ts";
import {
  cubicBezier,
  fluid,
  fontFamily,
  gradient,
  px,
  rem,
  round,
  shadow,
  type GradientShape,
} from "./css.ts";
import { getToken, isGroup, listTokens, referenceOf, resolve, type TokenTree } from "./tokens.ts";

const HEADER =
  "/* Generated by packages/tokens/scripts/build.ts from src/tokens.json. Do not edit; run pnpm tokens:build. */";

/**
 * Each semantic colour is exposed only through the Tailwind utility family it may be used with,
 * so `bg-page` and `text-muted` exist but `text-page` and `bg-muted` do not.
 */
export const COLOR_UTILITIES: readonly (readonly [cssVar: string, path: string])[] = [
  ["--background-color-page", "color.bg.page"],
  ["--background-color-alt", "color.bg.alt"],
  ["--background-color-card", "color.bg.card"],
  ["--background-color-brand", "color.bg.brand"],
  ["--background-color-band", "color.bg.band"],
  ["--background-color-action", "color.action.primary"],
  ["--background-color-action-pressed", "color.action.pressed"],
  ["--background-color-popular", "color.tag.popular"],
  ["--text-color-primary", "color.text.primary"],
  ["--text-color-muted", "color.text.muted"],
  ["--text-color-accent", "color.text.accent"],
  ["--text-color-brand", "color.text.brand"],
  ["--text-color-on-gold", "color.text.on-gold"],
  ["--text-color-good", "color.status.good"],
  ["--border-color-subtle", "color.border.subtle"],
  ["--border-color-strong", "color.border.strong"],
  ["--outline-color-focus", "color.focus"],
];

export interface BuildOutput {
  files: Record<"theme.css" | "tokens.css" | "base.css" | "tokens.ts", string>;
  /** Token path -> the CSS custom property that carries it. */
  cssVars: Record<string, string>;
}

type Line = string;

export function build(tree: TokenTree): BuildOutput {
  const consumed = new Set<string>();
  const cssVars: Record<string, string> = {};

  const value = (path: string): unknown => {
    consumed.add(path);
    return resolve(tree, getToken(tree, path).$value);
  };
  const text = (path: string): string => {
    const resolved = value(path);
    if (typeof resolved !== "string" && typeof resolved !== "number") {
      throw new Error(`{${path}} is not a string or number`);
    }
    return String(resolved);
  };
  const pixels = (path: string): number => px(value(path));
  const children = (path: string): string[] => {
    const group = path
      .split(".")
      .reduce<unknown>((node, key) => (isGroup(node) ? node[key] : undefined), tree);
    if (!isGroup(group)) throw new Error(`Unknown group: ${path}`);
    return Object.keys(group).filter((key) => !key.startsWith("$"));
  };
  /** Declares a custom property; the first declaration of a token becomes its canonical variable. */
  const declare = (name: string, css: string, path?: string): Line => {
    if (path !== undefined) {
      consumed.add(path);
      cssVars[path] ??= name;
    }
    return `  ${name}: ${css};`;
  };

  const fluidFrom = pixels("layout.breakpoint.sm");
  const fluidTo = pixels("layout.breakpoint.2xl");

  // ---------- theme.css: the Tailwind v4 theme. Only these utilities exist. ----------
  const theme: Line[] = [
    HEADER,
    "/* Tailwind's default theme is removed: only NGB tokens produce utilities. */",
    "@theme static {",
    "  --*: initial;",
    "",
    "  /* Breakpoints (board 05) */",
    ...children("layout.breakpoint").map((key) =>
      declare(
        `--breakpoint-${key}`,
        rem(pixels(`layout.breakpoint.${key}`)),
        `layout.breakpoint.${key}`,
      ),
    ),
    "",
    "  /* Colour (board 02): semantic roles only */",
    ...COLOR_UTILITIES.map(([name, path]) => declare(name, text(path), path)),
    "  --border-color-focus: var(--outline-color-focus);",
    "  --ring-color-focus: var(--outline-color-focus);",
    "",
    "  /* Typefaces and weights (board 04) */",
    ...children("font").map((key) => {
      // The primitive family carries the CSS variable its font loader sets (next/font in apps/web).
      const primitive = referenceOf(getToken(tree, `font.${key}`).$value);
      const loader =
        primitive === undefined ? undefined : getToken(tree, primitive).$extensions?.["ngb"];
      const cssVariable = (loader as { cssVariable?: string } | undefined)?.cssVariable;
      return declare(`--font-${key}`, fontFamily(value(`font.${key}`), cssVariable), `font.${key}`);
    }),
    "  --default-font-family: var(--font-body);",
    "  --default-mono-font-family: var(--font-data);",
    ...children("font-weight").map((key) =>
      declare(`--font-weight-${key}`, text(`font-weight.${key}`), `font-weight.${key}`),
    ),
    "",
    `  /* Type scale (board 04): fluid from ${fluidFrom} px to ${fluidTo} px viewports */`,
    ...children("line-height").map((key) =>
      declare(`--leading-${key}`, text(`line-height.${key}`), `line-height.${key}`),
    ),
    ...children("letter-spacing").map((key) =>
      declare(`--tracking-${key}`, text(`letter-spacing.${key}`), `letter-spacing.${key}`),
    ),
    ...children("type").flatMap((role) => {
      const mobile = pixels(`type.${role}.mobile`);
      const desktop = pixels(`type.${role}.desktop`);
      cssVars[`type.${role}.mobile`] = `--text-${role}`;
      cssVars[`type.${role}.desktop`] = `--text-${role}`;
      // Optional per-role line height and tracking, applied automatically by the text-<role> class.
      const modifiers = children(`type.${role}`)
        .filter((key) => key === "line-height" || key === "letter-spacing")
        .map((key) => {
          const path = `type.${role}.${key}`;
          const reference = referenceOf(getToken(tree, path).$value);
          const target = reference === undefined ? undefined : cssVars[reference];
          return declare(`--text-${role}--${key}`, target ? `var(${target})` : text(path), path);
        });
      return [declare(`--text-${role}`, fluid(mobile, desktop, fluidFrom, fluidTo)), ...modifiers];
    }),
    "",
    "  /* Spacing (board 05): p-16 = 16 px. Only the scale steps exist. */",
    ...children("primitive.space").map((key) =>
      declare(`--spacing-${key}`, rem(pixels(`primitive.space.${key}`)), `primitive.space.${key}`),
    ),
    declare(
      "--spacing-section-top",
      fluid(
        pixels("space.section.top-mobile"),
        pixels("space.section.top-desktop"),
        fluidFrom,
        fluidTo,
      ),
      "space.section.top-mobile",
    ),
    declare(
      "--spacing-section-bottom",
      fluid(
        pixels("space.section.bottom-mobile"),
        pixels("space.section.bottom-desktop"),
        fluidFrom,
        fluidTo,
      ),
      "space.section.bottom-mobile",
    ),
    declare("--spacing-target", rem(pixels("space.target")), "space.target"),
    declare("--spacing-target-gap", rem(pixels("space.target-gap")), "space.target-gap"),
    "  --spacing-page: var(--layout-margin);",
    "  --spacing-gutter: var(--layout-gutter);",
    "  --spacing-nav: var(--layout-nav-height);",
    "",
    "  /* Widths */",
    declare("--container-content", rem(pixels("layout.content-max")), "layout.content-max"),
    declare("--container-measure", `${text("measure.body-max")}ch`, "measure.body-max"),
    declare("--container-lead", `${text("measure.lead-max")}ch`, "measure.lead-max"),
    "",
    "  /* Shape and depth (boards 03, 05) */",
    ...children("shape.radius").map((key) =>
      declare(`--radius-${key}`, rem(pixels(`shape.radius.${key}`)), `shape.radius.${key}`),
    ),
    ...children("shadow").map((key) =>
      declare(`--shadow-${key}`, shadow(value(`shadow.${key}`)), `shadow.${key}`),
    ),
    "",
    "  /* Motion (board 09) */",
    ...children("motion.easing").map((key) =>
      declare(`--ease-${key}`, cubicBezier(value(`motion.easing.${key}`)), `motion.easing.${key}`),
    ),
    `  --default-transition-duration: ${text("motion.duration.fast")};`,
    "  --default-transition-timing-function: var(--ease-out);",
    "}",
    "",
  ];
  consumed.add("space.section.top-desktop").add("space.section.bottom-desktop");
  cssVars["space.section.top-desktop"] = "--spacing-section-top";
  cssVars["space.section.bottom-desktop"] = "--spacing-section-bottom";

  // ---------- tokens.css: values that are not Tailwind utilities ----------
  const grid = (size: "mobile" | "tablet" | "desktop"): Line[] => [
    declare("--layout-columns", text(`layout.grid.${size}.columns`), `layout.grid.${size}.columns`),
    declare(
      "--layout-margin",
      rem(pixels(`layout.grid.${size}.margin`)),
      `layout.grid.${size}.margin`,
    ),
    declare(
      "--layout-gutter",
      rem(pixels(`layout.grid.${size}.gutter`)),
      `layout.grid.${size}.gutter`,
    ),
  ];
  const gradients = children("gradient").map((key) => {
    const token = getToken(tree, `gradient.${key}`);
    const shape = token.$extensions?.["ngb"] as GradientShape | undefined;
    if (!shape) throw new Error(`{gradient.${key}} needs $extensions.ngb with its shape`);
    return declare(
      `--gradient-${key}`,
      gradient(value(`gradient.${key}`), shape),
      `gradient.${key}`,
    );
  });

  const root: Line[] = [
    "  /* Ember gradient and ghost word (board 03) */",
    ...gradients,
    "",
    "  /* Motion (board 09) */",
    ...children("motion.duration").map((key) =>
      declare(`--motion-${key}`, text(`motion.duration.${key}`), `motion.duration.${key}`),
    ),
    ...children("motion.lift").map((key) =>
      declare(`--motion-lift-${key}`, `${pixels(`motion.lift.${key}`)}px`, `motion.lift.${key}`),
    ),
    "",
    "  /* Shape (board 05): drawn only by the brand utilities in packages/ui */",
    ...children("shape.chamfer").map((key) =>
      declare(
        `--shape-chamfer-${key}`,
        `${pixels(`shape.chamfer.${key}`)}px`,
        `shape.chamfer.${key}`,
      ),
    ),
    declare("--shape-lean", `${text("shape.lean")}deg`, "shape.lean"),
    "",
    "  /* Icons (board 06) and stacking order */",
    ...children("icon").map((key) =>
      declare(`--icon-${key}`, rem(pixels(`icon.${key}`)), `icon.${key}`),
    ),
    ...children("layer").map((key) =>
      declare(`--layer-${key}`, text(`layer.${key}`), `layer.${key}`),
    ),
    declare("--measure-body-min", `${text("measure.body-min")}ch`, "measure.body-min"),
    "",
    "  /* Layout (board 05): mobile first */",
    ...grid("mobile"),
    declare(
      "--layout-nav-height",
      rem(pixels("layout.nav-height.mobile")),
      "layout.nav-height.mobile",
    ),
  ];

  // Component tier last, so references can point at the variables declared above.
  const component: Line[] = listTokens(tree)
    .filter(({ path }) => path.startsWith("component."))
    .map(({ path, token, type }) => {
      const name = `--${path.slice("component.".length).replaceAll(".", "-")}`;
      const reference = referenceOf(token.$value);
      const target = reference === undefined ? undefined : cssVars[reference];
      if (target !== undefined) return declare(name, `var(${target})`, path);
      const resolved = value(path);
      if (type === "dimension") {
        const size = px(resolved);
        // Hairlines stay in px; everything else scales with the user's font size.
        return declare(name, size <= 2 ? `${size}px` : rem(size), path);
      }
      if (type === "shadow") return declare(name, shadow(resolved), path);
      return declare(name, String(resolved), path);
    });

  const tokensCss = [
    HEADER,
    ":root {",
    ...root,
    "",
    "  /* Component tier: used by one component each */",
    ...component,
    "}",
    "",
    "@media (min-width: 48rem) {",
    "  :root {",
    ...grid("tablet").map((line) => `  ${line}`),
    "  }",
    "}",
    "",
    "@media (min-width: 64rem) {",
    "  :root {",
    ...grid("desktop").map((line) => `  ${line}`),
    `  ${declare("--layout-nav-height", rem(pixels("layout.nav-height.desktop")), "layout.nav-height.desktop")}`,
    "  }",
    "}",
    "",
  ].join("\n");

  // ---------- base.css: document defaults ----------
  const baseCss = [
    HEADER,
    "@layer base {",
    "  html {",
    "    background-color: var(--background-color-page);",
    "    color: var(--text-color-primary);",
    "    color-scheme: dark;",
    "    -webkit-font-smoothing: antialiased;",
    "    -moz-osx-font-smoothing: grayscale;",
    "    text-size-adjust: 100%;",
    "  }",
    "",
    "  body {",
    "    font-size: var(--text-body);",
    "    line-height: var(--leading-body);",
    "  }",
    "",
    "  /* Telugu needs room for vowel signs above and below, so every role uses the Telugu line height. */",
    "  :lang(te) {",
    "    font-family: var(--font-telugu-body);",
    "    line-height: var(--leading-telugu);",
    ...children("type")
      .filter((role) => children(`type.${role}`).includes("line-height"))
      .map((role) => `    --text-${role}--line-height: var(--leading-telugu);`),
    "    /* Rush Driver and GT America have no Telugu glyphs: display, heading and label roles use Anek Telugu. */",
    "    --font-display: var(--font-telugu-heading);",
    "    --font-heading: var(--font-telugu-heading);",
    "    --font-label: var(--font-telugu-heading);",
    "    --font-body: var(--font-telugu-body);",
    "    /* Letter-spacing turns off the ligatures that join Telugu conjuncts, so tracking is removed. */",
    ...children("type")
      .filter((role) => children(`type.${role}`).includes("letter-spacing"))
      .map((role) => `    --text-${role}--letter-spacing: normal;`),
    "  }",
    "",
    "  ::selection {",
    "    background-color: var(--background-color-brand);",
    "    color: var(--text-color-primary);",
    "  }",
    "",
    "  /* Mirrors shadow.focus: a 2 px gap in the page colour, then a 2 px signal red ring. */",
    "  :focus-visible {",
    "    outline: 2px solid var(--outline-color-focus);",
    "    outline-offset: 2px;",
    "  }",
    "",
    "  /* The page's one marquee (screen A6): two copies of the row slide left by one copy's width. */",
    "  @keyframes ngb-marquee {",
    "    to {",
    "      transform: translateX(-50%);",
    "    }",
    "  }",
    "",
    "  /* Reduced motion (board 09): fades only; no movement, pinning or parallax. */",
    "  @media (prefers-reduced-motion: reduce) {",
    "    *,",
    "    ::before,",
    "    ::after {",
    "      animation-duration: 0.01ms !important;",
    "      animation-iteration-count: 1 !important;",
    "      transition-duration: 0.01ms !important;",
    "      scroll-behavior: auto !important;",
    "    }",
    "  }",
    "}",
    "",
  ].join("\n");

  // ---------- tokens.ts: typed values for code (GSAP timings, theme colour, Foundations page) ----------
  const values: TokenTree = {};
  for (const { path } of listTokens(tree)) {
    if (path.startsWith("primitive.")) continue;
    const keys = path.split(".");
    const leaf = keys.pop() ?? "";
    let node = values;
    for (const key of keys) {
      node[key] ??= {};
      node = node[key] as TokenTree;
    }
    node[leaf] = resolve(tree, getToken(tree, path).$value);
  }
  const hex = (path: string): string => text(path);
  const contrast = approvedPairs.map((pair) => {
    const ratio = round(contrastRatio(hex(pair.foreground), hex(pair.background)), 2);
    return {
      ...pair,
      foregroundHex: hex(pair.foreground),
      backgroundHex: hex(pair.background),
      ratio,
      passes: ratio >= pair.minimum,
    };
  });
  const forbidden = forbiddenPairs.map((pair) => ({
    ...pair,
    foregroundHex: hex(pair.foreground),
    backgroundHex: hex(pair.background),
    ratio: round(contrastRatio(hex(pair.foreground), hex(pair.background)), 2),
  }));

  const tokensTs = [
    "// Generated by packages/tokens/scripts/build.ts from src/tokens.json. Do not edit; run pnpm tokens:build.",
    "",
    "/** Resolved semantic and component tokens. Primitives are intentionally not exported. */",
    `export const tokens = ${JSON.stringify(values, null, 2)} as const;`,
    "",
    "/** Token path -> CSS custom property. */",
    `export const cssVars = ${JSON.stringify(cssVars, null, 2)} as const;`,
    "",
    "/** Board 02 pairs with their computed WCAG ratio. */",
    `export const contrast = ${JSON.stringify(contrast, null, 2)} as const;`,
    "",
    "/** Pairs board 02 forbids, with their computed ratio. */",
    `export const forbiddenContrast = ${JSON.stringify(forbidden, null, 2)} as const;`,
    "",
    "export type Tokens = typeof tokens;",
    "",
  ].join("\n");

  // Every non-primitive token must reach the output; an unused token is a bug.
  const missing = listTokens(tree)
    .map(({ path }) => path)
    .filter((path) => !path.startsWith("primitive.") && !consumed.has(path));
  if (missing.length > 0) {
    throw new Error(`These tokens are not emitted by the build: ${missing.join(", ")}`);
  }

  return {
    files: {
      "theme.css": theme.join("\n"),
      "tokens.css": tokensCss,
      "base.css": baseCss,
      "tokens.ts": tokensTs,
    },
    cssVars,
  };
}
